// import type { Transaction } from './types'

// export const transactions: Transaction[] = [
//   {
//     id: '1',
//     type: 'income',
//     amount: 1200,
//     description: 'Salary payment',
//     category: 'Salary',
//     date: new Date('2025-01-01'),
//     account: 'Main Account',
//   },
//   {
//     id: '2',
//     type: 'expense',
//     amount: 50,
//     description: 'Grocery shopping',
//     category: 'Food',
//     date: new Date('2025-01-02'),
//     account: 'Personal Account',
//   },
//   {
//     id: '3',
//     type: 'expense',
//     amount: 25,
//     description: 'Coffee with friends',
//     category: 'Leisure',
//     date: new Date('2025-01-02'),
//     account: 'Main Account',
//   },
//   {
//     id: '4',
//     type: 'income',
//     amount: 200,
//     description: 'Freelance work',
//     category: 'Income',
//     date: new Date('2025-01-03'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '5',
//     type: 'expense',
//     amount: 150,
//     description: 'Dining out',
//     category: 'Food',
//     date: new Date('2025-01-04'),
//     account: 'Personal Account',
//   },
//   {
//     id: '6',
//     type: 'expense',
//     amount: 90,
//     description: 'Utility bill',
//     category: 'Utilities',
//     date: new Date('2025-01-05'),
//     account: 'Main Account',
//   },
//   {
//     id: '7',
//     type: 'transfer',
//     amount: 500,
//     description: 'Transfer to savings',
//     category: 'Transfer',
//     date: new Date('2025-01-06'),
//     account: 'Main Account',
//   },
//   {
//     id: '8',
//     type: 'income',
//     amount: 600,
//     description: 'Part-time job',
//     category: 'Income',
//     date: new Date('2025-01-07'),
//     account: 'Main Account',
//   },
//   {
//     id: '9',
//     type: 'expense',
//     amount: 200,
//     description: 'Rent payment',
//     category: 'Housing',
//     date: new Date('2025-01-08'),
//     account: 'Housing Account',
//   },
//   {
//     id: '10',
//     type: 'expense',
//     amount: 75,
//     description: 'Gas refill',
//     category: 'Transportation',
//     date: new Date('2025-01-09'),
//     account: 'Car Account',
//   },
//   {
//     id: '11',
//     type: 'expense',
//     amount: 120,
//     description: 'Movie night',
//     category: 'Leisure',
//     date: new Date('2025-01-10'),
//     account: 'Entertainment Account',
//   },
//   {
//     id: '12',
//     type: 'income',
//     amount: 1000,
//     description: 'Freelance project',
//     category: 'Income',
//     date: new Date('2025-01-11'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '13',
//     type: 'expense',
//     amount: 300,
//     description: 'Car insurance',
//     category: 'Insurance',
//     date: new Date('2025-01-12'),
//     account: 'Car Account',
//   },
//   {
//     id: '14',
//     type: 'expense',
//     amount: 60,
//     description: 'Gym membership',
//     category: 'Health',
//     date: new Date('2025-01-13'),
//     account: 'Health Account',
//   },
//   {
//     id: '15',
//     type: 'income',
//     amount: 450,
//     description: 'Payment from client',
//     category: 'Income',
//     date: new Date('2025-01-14'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '16',
//     type: 'expense',
//     amount: 25,
//     description: 'Lunch with a colleague',
//     category: 'Leisure',
//     date: new Date('2025-01-15'),
//     account: 'Personal Account',
//   },
//   {
//     id: '17',
//     type: 'transfer',
//     amount: 200,
//     description: 'Transfer to investment',
//     category: 'Transfer',
//     date: new Date('2025-01-16'),
//     account: 'Main Account',
//   },
//   {
//     id: '18',
//     type: 'expense',
//     amount: 350,
//     description: 'Travel expenses',
//     category: 'Transportation',
//     date: new Date('2025-01-17'),
//     account: 'Travel Account',
//   },
//   {
//     id: '19',
//     type: 'income',
//     amount: 800,
//     description: 'Consulting income',
//     category: 'Income',
//     date: new Date('2025-01-18'),
//     account: 'Consulting Account',
//   },
//   {
//     id: '20',
//     type: 'expense',
//     amount: 100,
//     description: 'Shopping for clothes',
//     category: 'Apparel',
//     date: new Date('2025-01-19'),
//     account: 'Shopping Account',
//   },
//   {
//     id: '21',
//     type: 'income',
//     amount: 250,
//     description: 'Bonus payment',
//     category: 'Bonus',
//     date: new Date('2025-01-20'),
//     account: 'Main Account',
//   },
//   {
//     id: '22',
//     type: 'expense',
//     amount: 30,
//     description: 'Takeout dinner',
//     category: 'Food',
//     date: new Date('2025-01-21'),
//     account: 'Personal Account',
//   },
//   {
//     id: '23',
//     type: 'expense',
//     amount: 120,
//     description: 'Electric bill',
//     category: 'Utilities',
//     date: new Date('2025-01-22'),
//     account: 'Main Account',
//   },
//   {
//     id: '24',
//     type: 'transfer',
//     amount: 300,
//     description: 'Transfer to emergency fund',
//     category: 'Transfer',
//     date: new Date('2025-01-23'),
//     account: 'Main Account',
//   },
//   {
//     id: '25',
//     type: 'expense',
//     amount: 85,
//     description: 'Books and supplies',
//     category: 'Education',
//     date: new Date('2025-01-24'),
//     account: 'Education Account',
//   },
//   {
//     id: '26',
//     type: 'income',
//     amount: 1500,
//     description: 'Freelance contract',
//     category: 'Income',
//     date: new Date('2025-01-25'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '27',
//     type: 'expense',
//     amount: 40,
//     description: 'Lunch at restaurant',
//     category: 'Food',
//     date: new Date('2025-01-26'),
//     account: 'Dining Account',
//   },
//   {
//     id: '28',
//     type: 'expense',
//     amount: 180,
//     description: 'Mobile phone bill',
//     category: 'Utilities',
//     date: new Date('2025-01-27'),
//     account: 'Personal Account',
//   },
//   {
//     id: '29',
//     type: 'income',
//     amount: 750,
//     description: 'Side business income',
//     category: 'Income',
//     date: new Date('2025-01-28'),
//     account: 'Side Business Account',
//   },
//   {
//     id: '30',
//     type: 'expense',
//     amount: 250,
//     description: 'Medical expenses',
//     category: 'Health',
//     date: new Date('2025-01-29'),
//     account: 'Health Account',
//   },
//   {
//     id: '31',
//     type: 'transfer',
//     amount: 400,
//     description: 'Transfer to savings',
//     category: 'Transfer',
//     date: new Date('2025-01-30'),
//     account: 'Main Account',
//   },
//   {
//     id: '32',
//     type: 'expense',
//     amount: 90,
//     description: 'Internet bill',
//     category: 'Utilities',
//     date: new Date('2025-02-01'),
//     account: 'Main Account',
//   },
//   {
//     id: '33',
//     type: 'income',
//     amount: 1200,
//     description: 'Full-time job salary',
//     category: 'Salary',
//     date: new Date('2025-02-02'),
//     account: 'Main Account',
//   },
//   {
//     id: '34',
//     type: 'expense',
//     amount: 50,
//     description: 'Lunch with a friend',
//     category: 'Food',
//     date: new Date('2025-02-03'),
//     account: 'Main Account',
//   },
//   {
//     id: '35',
//     type: 'income',
//     amount: 500,
//     description: 'Consulting work',
//     category: 'Income',
//     date: new Date('2025-02-04'),
//     account: 'Consulting Account',
//   },
//   {
//     id: '36',
//     type: 'expense',
//     amount: 120,
//     description: 'Shopping for groceries',
//     category: 'Food',
//     date: new Date('2025-02-05'),
//     account: 'Grocery Account',
//   },
//   {
//     id: '37',
//     type: 'expense',
//     amount: 200,
//     description: 'Rent payment',
//     category: 'Housing',
//     date: new Date('2025-02-06'),
//     account: 'Housing Account',
//   },
//   {
//     id: '38',
//     type: 'income',
//     amount: 450,
//     description: 'Project payment',
//     category: 'Income',
//     date: new Date('2025-02-07'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '39',
//     type: 'expense',
//     amount: 25,
//     description: 'Takeout lunch',
//     category: 'Food',
//     date: new Date('2025-02-08'),
//     account: 'Dining Account',
//   },
//   {
//     id: '40',
//     type: 'expense',
//     amount: 100,
//     description: 'Online subscription',
//     category: 'Entertainment',
//     date: new Date('2025-02-09'),
//     account: 'Entertainment Account',
//   },
//   {
//     id: '41',
//     type: 'income',
//     amount: 900,
//     description: 'Payment for services',
//     category: 'Income',
//     date: new Date('2025-02-10'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '42',
//     type: 'expense',
//     amount: 150,
//     description: 'Restaurant meal',
//     category: 'Food',
//     date: new Date('2025-02-11'),
//     account: 'Personal Account',
//   },
//   {
//     id: '43',
//     type: 'income',
//     amount: 400,
//     description: 'Online course sale',
//     category: 'Income',
//     date: new Date('2025-02-12'),
//     account: 'Business Account',
//   },
//   {
//     id: '44',
//     type: 'expense',
//     amount: 60,
//     description: 'Subscription service',
//     category: 'Entertainment',
//     date: new Date('2025-02-13'),
//     account: 'Entertainment Account',
//   },
//   {
//     id: '45',
//     type: 'transfer',
//     amount: 100,
//     description: 'Transfer to retirement account',
//     category: 'Transfer',
//     date: new Date('2025-02-14'),
//     account: 'Main Account',
//   },
//   {
//     id: '46',
//     type: 'expense',
//     amount: 50,
//     description: 'Lunch with a client',
//     category: 'Food',
//     date: new Date('2025-02-15'),
//     account: 'Business Account',
//   },
//   {
//     id: '47',
//     type: 'income',
//     amount: 1100,
//     description: 'Freelance payment',
//     category: 'Income',
//     date: new Date('2025-02-16'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '48',
//     type: 'expense',
//     amount: 75,
//     description: 'Uber ride',
//     category: 'Transportation',
//     date: new Date('2025-02-17'),
//     account: 'Personal Account',
//   },
//   {
//     id: '49',
//     type: 'expense',
//     amount: 100,
//     description: 'Pet supplies',
//     category: 'Pets',
//     date: new Date('2025-02-18'),
//     account: 'Pet Account',
//   },
//   {
//     id: '50',
//     type: 'income',
//     amount: 950,
//     description: 'Consulting income',
//     category: 'Income',
//     date: new Date('2025-02-19'),
//     account: 'Consulting Account',
//   },
//   {
//     id: '51',
//     type: 'expense',
//     amount: 30,
//     description: 'Fast food',
//     category: 'Food',
//     date: new Date('2025-02-20'),
//     account: 'Dining Account',
//   },
//   {
//     id: '52',
//     type: 'expense',
//     amount: 45,
//     description: 'Parking fee',
//     category: 'Transportation',
//     date: new Date('2025-02-21'),
//     account: 'Car Account',
//   },
//   {
//     id: '53',
//     type: 'income',
//     amount: 700,
//     description: 'E-commerce sales',
//     category: 'Sales',
//     date: new Date('2025-02-22'),
//     account: 'Business Account',
//   },
//   {
//     id: '54',
//     type: 'expense',
//     amount: 150,
//     description: 'Movie tickets',
//     category: 'Leisure',
//     date: new Date('2025-02-23'),
//     account: 'Entertainment Account',
//   },
//   {
//     id: '55',
//     type: 'income',
//     amount: 500,
//     description: 'Payment for contract work',
//     category: 'Income',
//     date: new Date('2025-02-24'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '56',
//     type: 'expense',
//     amount: 120,
//     description: 'Utilities payment',
//     category: 'Utilities',
//     date: new Date('2025-02-25'),
//     account: 'Main Account',
//   },
//   {
//     id: '57',
//     type: 'income',
//     amount: 350,
//     description: 'Side gig payment',
//     category: 'Income',
//     date: new Date('2025-02-26'),
//     account: 'Side Business Account',
//   },
//   {
//     id: '58',
//     type: 'expense',
//     amount: 80,
//     description: 'Entertainment subscription',
//     category: 'Entertainment',
//     date: new Date('2025-02-27'),
//     account: 'Entertainment Account',
//   },
//   {
//     id: '59',
//     type: 'transfer',
//     amount: 500,
//     description: 'Transfer to investment',
//     category: 'Transfer',
//     date: new Date('2025-02-28'),
//     account: 'Main Account',
//   },
//   {
//     id: '60',
//     type: 'expense',
//     amount: 30,
//     description: 'Snacks',
//     category: 'Food',
//     date: new Date('2025-03-01'),
//     account: 'Personal Account',
//   },
//   {
//     id: '61',
//     type: 'income',
//     amount: 1300,
//     description: 'Salary for March',
//     category: 'Salary',
//     date: new Date('2025-03-02'),
//     account: 'Main Account',
//   },
//   {
//     id: '62',
//     type: 'expense',
//     amount: 70,
//     description: 'Lunch at cafe',
//     category: 'Food',
//     date: new Date('2025-03-03'),
//     account: 'Personal Account',
//   },
//   {
//     id: '63',
//     type: 'expense',
//     amount: 180,
//     description: 'Health insurance premium',
//     category: 'Insurance',
//     date: new Date('2025-03-04'),
//     account: 'Health Account',
//   },
//   {
//     id: '64',
//     type: 'income',
//     amount: 400,
//     description: 'Online service payment',
//     category: 'Income',
//     date: new Date('2025-03-05'),
//     account: 'Business Account',
//   },
//   {
//     id: '65',
//     type: 'expense',
//     amount: 25,
//     description: 'Ice cream',
//     category: 'Food',
//     date: new Date('2025-03-06'),
//     account: 'Personal Account',
//   },
//   {
//     id: '66',
//     type: 'expense',
//     amount: 50,
//     description: 'Book purchase',
//     category: 'Leisure',
//     date: new Date('2025-03-07'),
//     account: 'Reading Account',
//   },
//   {
//     id: '67',
//     type: 'income',
//     amount: 700,
//     description: 'Freelance project',
//     category: 'Income',
//     date: new Date('2025-03-08'),
//     account: 'Freelance Account',
//   },
//   {
//     id: '68',
//     type: 'expense',
//     amount: 95,
//     description: 'Takeout dinner',
//     category: 'Food',
//     date: new Date('2025-03-09'),
//     account: 'Dining Account',
//   },
//   {
//     id: '69',
//     type: 'transfer',
//     amount: 600,
//     description: 'Transfer to savings',
//     category: 'Transfer',
//     date: new Date('2025-03-10'),
//     account: 'Main Account',
//   },
//   {
//     id: '70',
//     type: 'income',
//     amount: 500,
//     description: 'Bonus payment',
//     category: 'Bonus',
//     date: new Date('2025-03-11'),
//     account: 'Main Account',
//   },
// ]

import type { Transaction } from './types'

export const transactions: Transaction[] = [
  {
    id: '1',
    type: 'income',
    amount: 1200,
    description: 'Salary payment',
    category: 'Salary',
    date: '2025-01-02',
    account: 'Main Account',
  },
  {
    id: '2',
    type: 'expense',
    amount: 50,
    description: 'Grocery shopping',
    category: 'Food',
    date: '2025-01-01',
    account: 'Personal Account',
  },
  {
    id: '3',
    type: 'expense',
    amount: 25,
    description: 'Coffee with friends',
    category: 'Leisure',
    date: '2025-01-01',
    account: 'Main Account',
  },
  {
    id: '4',
    type: 'income',
    amount: 200,
    description: 'Freelance work',
    category: 'Income',
    date: '2024-12-30',
    account: 'Freelance Account',
  },
  {
    id: '5',
    type: 'expense',
    amount: 150,
    description: 'Dining out',
    category: 'Food',
    date: '2024-12-29',
    account: 'Personal Account',
  },
  {
    id: '6',
    type: 'expense',
    amount: 90,
    description: 'Utility bill',
    category: 'Utilities',
    date: '2024-12-28',
    account: 'Main Account',
  },
  {
    id: '7',
    type: 'transfer',
    amount: 500,
    description: 'Transfer to savings',
    category: 'Transfer',
    date: '2024-12-27',
    account: 'Main Account',
  },
  {
    id: '8',
    type: 'income',
    amount: 600,
    description: 'Part-time job',
    category: 'Income',
    date: '2024-12-26',
    account: 'Main Account',
  },
  {
    id: '9',
    type: 'expense',
    amount: 200,
    description: 'Rent payment',
    category: 'Housing',
    date: '2024-12-25',
    account: 'Housing Account',
  },
  {
    id: '10',
    type: 'expense',
    amount: 75,
    description: 'Gas refill',
    category: 'Transportation',
    date: '2024-12-24',
    account: 'Car Account',
  },
  {
    id: '11',
    type: 'expense',
    amount: 120,
    description: 'Movie night',
    category: 'Leisure',
    date: '2024-12-23',
    account: 'Entertainment Account',
  },
  {
    id: '12',
    type: 'income',
    amount: 1000,
    description: 'Freelance project',
    category: 'Income',
    date: '2024-12-22',
    account: 'Freelance Account',
  },
  {
    id: '13',
    type: 'expense',
    amount: 300,
    description: 'Car insurance',
    category: 'Insurance',
    date: '2024-12-21',
    account: 'Car Account',
  },
  {
    id: '14',
    type: 'expense',
    amount: 60,
    description: 'Gym membership',
    category: 'Health',
    date: '2024-12-20',
    account: 'Health Account',
  },
  {
    id: '15',
    type: 'income',
    amount: 450,
    description: 'Payment from client',
    category: 'Income',
    date: '2024-12-19',
    account: 'Freelance Account',
  },
  {
    id: '16',
    type: 'expense',
    amount: 25,
    description: 'Lunch with a colleague',
    category: 'Leisure',
    date: '2024-12-18',
    account: 'Personal Account',
  },
  {
    id: '17',
    type: 'transfer',
    amount: 200,
    description: 'Transfer to investment',
    category: 'Transfer',
    date: '2024-12-17',
    account: 'Main Account',
  },
  {
    id: '18',
    type: 'expense',
    amount: 350,
    description: 'Travel expenses',
    category: 'Transportation',
    date: '2024-12-16',
    account: 'Travel Account',
  },
  {
    id: '19',
    type: 'income',
    amount: 800,
    description: 'Consulting income',
    category: 'Income',
    date: '2024-12-15',
    account: 'Consulting Account',
  },
  {
    id: '20',
    type: 'expense',
    amount: 100,
    description: 'Shopping for clothes',
    category: 'Apparel',
    date: '2024-12-14',
    account: 'Shopping Account',
  },
  {
    id: '21',
    type: 'income',
    amount: 250,
    description: 'Bonus payment',
    category: 'Bonus',
    date: '2024-12-13',
    account: 'Main Account',
  },
  {
    id: '22',
    type: 'expense',
    amount: 30,
    description: 'Takeout dinner',
    category: 'Food',
    date: '2024-12-12',
    account: 'Personal Account',
  },
  {
    id: '23',
    type: 'expense',
    amount: 120,
    description: 'Electric bill',
    category: 'Utilities',
    date: '2024-12-11',
    account: 'Main Account',
  },
  {
    id: '24',
    type: 'transfer',
    amount: 300,
    description: 'Transfer to emergency fund',
    category: 'Transfer',
    date: '2024-12-10',
    account: 'Main Account',
  },
  {
    id: '25',
    type: 'expense',
    amount: 85,
    description: 'Books and supplies',
    category: 'Education',
    date: '2024-12-09',
    account: 'Education Account',
  },
  {
    id: '26',
    type: 'income',
    amount: 1500,
    description: 'Freelance contract',
    category: 'Income',
    date: '2024-12-08',
    account: 'Freelance Account',
  },
  {
    id: '27',
    type: 'expense',
    amount: 40,
    description: 'Lunch at restaurant',
    category: 'Food',
    date: '2024-12-07',
    account: 'Dining Account',
  },
  {
    id: '28',
    type: 'expense',
    amount: 180,
    description: 'Mobile phone bill',
    category: 'Utilities',
    date: '2024-12-06',
    account: 'Personal Account',
  },
  {
    id: '29',
    type: 'income',
    amount: 750,
    description: 'Side business income',
    category: 'Income',
    date: '2024-12-05',
    account: 'Side Business Account',
  },
  {
    id: '30',
    type: 'expense',
    amount: 250,
    description: 'Medical expenses',
    category: 'Health',
    date: '2024-12-04',
    account: 'Health Account',
  },
  {
    id: '31',
    type: 'transfer',
    amount: 400,
    description: 'Transfer to savings',
    category: 'Transfer',
    date: '2024-12-03',
    account: 'Main Account',
  },
  {
    id: '32',
    type: 'expense',
    amount: 90,
    description: 'Internet bill',
    category: 'Utilities',
    date: '2024-12-02',
    account: 'Main Account',
  },
  {
    id: '33',
    type: 'income',
    amount: 1200,
    description: 'Full-time job salary',
    category: 'Salary',
    date: '2024-12-01',
    account: 'Main Account',
  },
  {
    id: '34',
    type: 'expense',
    amount: 50,
    description: 'Lunch with a friend',
    category: 'Food',
    date: '2024-11-30',
    account: 'Main Account',
  },
  {
    id: '35',
    type: 'income',
    amount: 500,
    description: 'Consulting work',
    category: 'Income',
    date: '2024-11-29',
    account: 'Consulting Account',
  },
  {
    id: '36',
    type: 'expense',
    amount: 150,
    description: 'Dining out',
    category: 'Food',
    date: '2024-11-28',
    account: 'Dining Account',
  },
  {
    id: '37',
    type: 'income',
    amount: 450,
    description: 'Freelance project',
    category: 'Income',
    date: '2024-11-27',
    account: 'Freelance Account',
  },
  {
    id: '38',
    type: 'expense',
    amount: 80,
    description: 'Electricity bill',
    category: 'Utilities',
    date: '2024-11-26',
    account: 'Main Account',
  },
  {
    id: '39',
    type: 'income',
    amount: 700,
    description: 'Freelance payment',
    category: 'Income',
    date: '2024-11-25',
    account: 'Freelance Account',
  },
  {
    id: '40',
    type: 'expense',
    amount: 100,
    description: 'Restaurant dinner',
    category: 'Food',
    date: '2024-11-24',
    account: 'Dining Account',
  },
  {
    id: '41',
    type: 'income',
    amount: 600,
    description: 'Part-time income',
    category: 'Income',
    date: '2024-11-23',
    account: 'Part-time Account',
  },
  {
    id: '42',
    type: 'expense',
    amount: 40,
    description: 'Lunch at cafe',
    category: 'Food',
    date: '2024-11-22',
    account: 'Personal Account',
  },
  {
    id: '43',
    type: 'income',
    amount: 1200,
    description: 'Full-time job salary',
    category: 'Salary',
    date: '2024-11-21',
    account: 'Main Account',
  },
  {
    id: '44',
    type: 'expense',
    amount: 150,
    description: 'Utilities bill',
    category: 'Utilities',
    date: '2024-11-20',
    account: 'Main Account',
  },
  {
    id: '45',
    type: 'expense',
    amount: 50,
    description: 'Snacks and drinks',
    category: 'Food',
    date: '2024-11-19',
    account: 'Personal Account',
  },
  {
    id: '46',
    type: 'income',
    amount: 400,
    description: 'Consulting payment',
    category: 'Income',
    date: '2024-11-18',
    account: 'Consulting Account',
  },
  {
    id: '47',
    type: 'expense',
    amount: 300,
    description: 'Medical treatment',
    category: 'Health',
    date: '2024-11-17',
    account: 'Health Account',
  },
  {
    id: '48',
    type: 'transfer',
    amount: 500,
    description: 'Transfer to savings account',
    category: 'Transfer',
    date: '2024-11-16',
    account: 'Main Account',
  },
  {
    id: '49',
    type: 'expense',
    amount: 40,
    description: 'Coffee at café',
    category: 'Leisure',
    date: '2024-11-15',
    account: 'Leisure Account',
  },
  {
    id: '50',
    type: 'income',
    amount: 900,
    description: 'Freelance payment',
    category: 'Income',
    date: '2024-11-14',
    account: 'Freelance Account',
  },
  {
    id: '51',
    type: 'expense',
    amount: 200,
    description: 'Rent payment',
    category: 'Housing',
    date: '2024-11-13',
    account: 'Housing Account',
  },
  {
    id: '52',
    type: 'income',
    amount: 800,
    description: 'Consulting work',
    category: 'Income',
    date: '2024-11-12',
    account: 'Consulting Account',
  },
  {
    id: '53',
    type: 'expense',
    amount: 150,
    description: 'Dining out',
    category: 'Food',
    date: '2024-11-11',
    account: 'Dining Account',
  },
  {
    id: '54',
    type: 'expense',
    amount: 20,
    description: 'Coffee break',
    category: 'Leisure',
    date: '2024-11-10',
    account: 'Personal Account',
  },
  {
    id: '55',
    type: 'income',
    amount: 600,
    description: 'Consulting fee',
    category: 'Income',
    date: '2024-11-09',
    account: 'Consulting Account',
  },
  {
    id: '56',
    type: 'expense',
    amount: 45,
    description: 'Lunch with client',
    category: 'Food',
    date: '2024-11-08',
    account: 'Business Account',
  },
  {
    id: '57',
    type: 'income',
    amount: 1000,
    description: 'Consulting payment',
    category: 'Income',
    date: '2024-11-07',
    account: 'Consulting Account',
  },
  {
    id: '58',
    type: 'expense',
    amount: 200,
    description: 'Car repair',
    category: 'Transportation',
    date: '2024-11-06',
    account: 'Car Account',
  },
  {
    id: '59',
    type: 'income',
    amount: 350,
    description: 'Freelance project',
    category: 'Income',
    date: '2024-11-05',
    account: 'Freelance Account',
  },
  {
    id: '60',
    type: 'expense',
    amount: 90,
    description: 'Groceries shopping',
    category: 'Food',
    date: '2024-11-04',
    account: 'Personal Account',
  },
  {
    id: '61',
    type: 'income',
    amount: 500,
    description: 'Consulting work',
    category: 'Income',
    date: '2024-11-03',
    account: 'Consulting Account',
  },
  {
    id: '62',
    type: 'expense',
    amount: 60,
    description: 'Lunch with friends',
    category: 'Leisure',
    date: '2024-11-02',
    account: 'Dining Account',
  },
  {
    id: '63',
    type: 'income',
    amount: 200,
    description: 'Freelance payment',
    category: 'Income',
    date: '2024-11-01',
    account: 'Freelance Account',
  },
  {
    id: '64',
    type: 'expense',
    amount: 180,
    description: 'Utility bills',
    category: 'Utilities',
    date: '2024-10-31',
    account: 'Main Account',
  },
  {
    id: '65',
    type: 'income',
    amount: 950,
    description: 'Consulting job',
    category: 'Income',
    date: '2024-10-30',
    account: 'Consulting Account',
  },
  {
    id: '66',
    type: 'expense',
    amount: 30,
    description: 'Coffee shop visit',
    category: 'Leisure',
    date: '2024-10-29',
    account: 'Personal Account',
  },
  {
    id: '67',
    type: 'income',
    amount: 1100,
    description: 'Consulting project',
    category: 'Income',
    date: '2024-10-28',
    account: 'Consulting Account',
  },
  {
    id: '68',
    type: 'expense',
    amount: 50,
    description: 'Car parking fees',
    category: 'Transportation',
    date: '2024-10-27',
    account: 'Car Account',
  },
  {
    id: '69',
    type: 'income',
    amount: 1000,
    description: 'Freelance income',
    category: 'Income',
    date: '2024-10-26',
    account: 'Freelance Account',
  },
  {
    id: '70',
    type: 'expense',
    amount: 250,
    description: 'Health checkup',
    category: 'Health',
    date: '2024-10-25',
    account: 'Health Account',
  },
]
